spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/unsaidcebu}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
app.security.allowed-origins=${ALLOWED_ORIGINS:http://localhost:3000}
