# Updated to use Session Pooler (IPv4 compatible)
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres
# Note: The username for the pooler is often different (includes your project ref)
spring.datasource.username=postgres.ddybaipugbtjeyyvdkgz
spring.datasource.password=ASA2NVui28750ZGH

# Hibernate auto-creation settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true